[mgr]
ratio = [ 2, 3, 4 ]
show_hidden = true

[opener]
editor = [
    { run = "$EDITOR %s", block = true, for = "unix", desc = "Open with default editor" },
]
m3u_player = [
    { run = "celluloid %s", orphan = true, for = "unix", desc = "Open .m3u with Celluloid" },
]

[open]
rules = [
    { url = "*.m3u", use = ["m3u_player", "open"] },
    { mime = "text/*", use = ["editor", "open"] },
    { url = "*", use = ["open"] },
]
